services:
  - type: web
    name: xcoinpay-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: OWNER_EMAIL
        sync: false

  - type: web
    name: xcoinpay-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run server
    envVars:
      - key: REACT_APP_API_URL
        value: https://xcoinpay-backend.onrender.com
